# Generated by Django 3.2.2 on 2021-05-09 01:11

from django.db import migrations, models
import shop_product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to=shop_product.models.upload_image_path, verbose_name='تصویر محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('visit_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('sale_count', models.IntegerField(default=0, verbose_name='تعداد فروش')),
                ('product_count', models.IntegerField(verbose_name='تعداد موجودی')),
                ('active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
