# Generated by Django 3.2.2 on 2021-05-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_category', '0001_initial'),
        ('shop_product', '0002_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='shop_category.Category', verbose_name='دسته بندی ها'),
        ),
    ]
