# Generated by Django 3.2.2 on 2021-05-09 21:23

from django.db import migrations, models
import shop_about.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to=shop_about.models.upload_image_path, verbose_name='عکس')),
                ('video', models.FileField(upload_to=shop_about.models.upload_video_path, verbose_name='ویدئو')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
