# Generated by Django 3.2.2 on 2021-05-10 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('family', models.CharField(max_length=120, verbose_name='نام خانوادگی')),
                ('city', models.CharField(max_length=120, verbose_name='شهر')),
                ('full_address', models.TextField(verbose_name='آدرس')),
                ('post_code', models.CharField(max_length=50, verbose_name='کدپستی')),
                ('phone_number', models.CharField(max_length=100, verbose_name='شماره تلفن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
    ]
