# Generated by Django 3.2.2 on 2021-05-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.IntegerField(max_length=50, verbose_name='کدپستی'),
        ),
    ]
