# Generated by Django 3.2.2 on 2021-05-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_address', '0002_alter_address_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.IntegerField(verbose_name='کدپستی'),
        ),
    ]
