# Generated by Django 3.2.2 on 2021-05-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان در url'),
        ),
    ]
