# Generated by Django 3.2.2 on 2021-05-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('keywords', models.CharField(max_length=300, verbose_name='کلمات کلیدی')),
                ('favicon', models.ImageField(upload_to='', verbose_name='آیکون سایت')),
                ('email', models.CharField(max_length=200, verbose_name='ایمیل سایت')),
                ('phone', models.CharField(max_length=200, verbose_name='شماره تلفن')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
