# Generated by Django 3.2.2 on 2021-05-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('email', models.EmailField(max_length=150, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=150, verbose_name='موضوع')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('status', models.BooleanField(default=False, verbose_name='خوانده شده / نشده')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس ها',
            },
        ),
    ]
