# Generated by Django 3.2.2 on 2021-05-11 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_address', '0003_alter_address_post_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_product', '0003_auto_20210509_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='رداخت شده / نشده')),
                ('payment_date', models.DateTimeField(verbose_name='تاریخ پرداخت')),
                ('is_send', models.BooleanField(default=False, verbose_name='ارسال شده / نشده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_address.address', verbose_name='آدرس ارسال')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت خرید')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_order.order', verbose_name='سبدخرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
    ]
