# Generated by Django 3.2.2 on 2021-05-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0002_auto_20210511_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات سبد خرید'},
        ),
    ]
